CodeSpotlightDefinitiveCmsBundle_login:
    pattern:  /backend/login
    defaults: { _controller: cs_cms.controller.backend.main:loginAction }

CodeSpotlightDefinitiveCmsBundle_login_check:
    pattern:  /backend/login_check
    requirements:
        method:   POST

CodeSpotlightDefinitiveCmsBundle_logout:
    pattern:  /backend/logout

CodeSpotlightDefinitiveCmsBundle_dashboard:
    pattern:  /backend
    defaults: { _controller: cs_cms.controller.backend.main:mainAction }
