parameters:
    # Controllers
    cs_cms.controller.backend.base.class: CodeSpotlight\Bundle\DefinitiveCmsBundle\Controller\BaseController
    cs_cms.controller.backend.main.class: CodeSpotlight\Bundle\DefinitiveCmsBundle\Controller\Backend\MainController

    # Security: Authentication Handlers
    cs_cms.security.authentication.success_handler.class: CodeSpotlight\Bundle\DefinitiveCmsBundle\Component\Security\Http\Authentication\AuthenticationSuccessHandler
    cs_cms.security.authentication.failure_handler.class: CodeSpotlight\Bundle\DefinitiveCmsBundle\Component\Security\Http\Authentication\AuthenticationFailureHandler

    # Session
    cs_cms.session.manager.class: CodeSpotlight\Bundle\DefinitiveCmsBundle\Session\SessionManager
services:
    # Controllers
    cs_cms.controller.backend.base:
        abstract: true
        class: %cs_cms.controller.backend.base.class%
        arguments: [@service_container]

    cs_cms.controller.backend.main:
        parent: cs_cms.controller.backend.base
        class: %cs_cms.controller.backend.main.class%

    # Security: Authentication Handlers
    cs_cms.security.authentication.success_handler:
        class: %cs_cms.security.authentication.success_handler.class%
        arguments: [@cs_cms.session.manager]

    cs_cms.security.authentication.failure_handler:
        class: %cs_cms.security.authentication.failure_handler.class%

    # Session
    cs_cms.session.manager:
      class: %cs_cms.session.manager.class%
      arguments: [@session]